dependencies:
  - matplotlib==3.4.2
  - networkx=2.4
  - numpy==1.19.5
  - pandas==1.0.5
  - scipy==1.2.1
  - tqdm==4.46.0
  - watermark==2.0.2
  - python-wget==3.2
  - scikit-learn
  - Cartopy==0.18.0
